### ISSUE TITLE
[BUG] Incorrect CORS header setting (or policy change?)

### ISSUE THREAD

**Issue by keiono** [MaayanLab/enrichr_issues#12]
**Describe the bug**
Before the migration to the new domain (http://maayanlab.cloud), our web application works perfectly when it calls Enrichr API for enrichment analysis on-the-fly.  However, this week, we noticed the old API no longer works.  We updated the URLs to the new ones in our application and "sometimes" it worked, but now it cannot access it anymore due to the following issue: 

`Access to fetch at 'http://maayanlab.cloud/Enrichr/addList' from origin 'http://hiview.ucsd.edu' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

Is this a policy change to block some of the 3rd party web applications or CORS setting has been misconfigured during the migration to new domain?

**To Reproduce**

Just call any API from JS code deployed as a part of web application.  All of them fails with the CORS header problem.

**Expected behavior**
Allow web application to access API without CORS error

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Mac OS 10.15.7 / Windows 10
 - Browser any modern browser (Chrome, Safari)
 - Version: After migration to http://maayanlab.cloud

**Comment by AviMaayan** [comment]
Dear @keiono if you change http to https it should work.

**Comment by keiono** [comment]
@AviMaayan  Oh, I did not noticed the new one supports HTTPS, and now it works.

Just FYI, the documentation and example code use http, instead of https, and some other developers may fall into the same issue. 

https://maayanlab.cloud/Enrichr/help#faq

Other than that, our API calls look OK for me.
Thanks for your help.

**Comment by maxim-k** [comment]
The API section of Help is fixed
