### ISSUE TITLE
[BUG] genesigdb outdated

### ISSUE THREAD

**Issue by dawe** [MaayanLab/enrichr_issues#14]
**Describe the bug**
If you perform any enrichment and check results in GeneSIGDB (Disease/Drugs), you can click on table entries to see the original entry. Unfortunately the [linked web site](http://www.genesigdb.org) is a chinese web site about, well… I don't really know what is about, but definitely not the intended database

**Comment by maxim-k** [comment]
Now the link points to the paper.
