### ISSUE TITLE
can a pathway be uploaded to Enrichr for use?

### ISSUE THREAD

**Issue by stinner21** [MaayanLab/enrichr_issues#18]
specifically, the MSigDB Hallmark 2020 Geneset converted to murine orthologs 

http://bioinf.wehi.edu.au/software/MSigDB/

publicly available online?

**Comment by AviMaayan** [comment]
It is already there under pathways... 
![image](https://user-images.githubusercontent.com/12749033/117230089-41a1b000-adea-11eb-9c96-139d2a1fff5c.png)

**Comment by stinner21** [comment]
So this version of MSIgDB is curated from human gene sets but the link above in the original comment contains an rdata file of the MSigDB hallmark pathways converted to murine orthologs. 

Which is potentially useful to those with mouse rna seq datasets.

just a suggestion, interested in your thoughts or whether mouse rna seq data can be analyzed with human pathways

**Comment by cybluetree** [comment]
It would be great if we could upload libraries. For example, KEGG, GO have updated versions. Is it possible to add this function so that we can use the latest version of database we are interested in? Thanks.

**Comment by AviMaayan** [comment]
You can use this new Appyter if you have customized library and/or background: https://appyters.maayanlab.cloud/#/Independent_Enrichment_Analysis
