### ISSUE TITLE
Is it possible to know if all gene names are recognized?

### ISSUE THREAD

**Issue by cybluetree** [MaayanLab/enrichr_issues#19]
Sometimes, there is inconsistency in gene names. One gene may have several names. Is there anyway to know if Enrichr recognize all gene names in the input gene list? Mis-recognition may lead to false positive or false negative results. Thanks!

**Comment by maxim-k** [comment]
Enrichr allows all strings with no special characters and considers them as gene names. What happens next depends on a specific gene set library. We treat source data with respect and modify it as less as possible.
I.e. the same gene is "MOP3" in "MGI Mammalian Phenotype 2013" and "ARNTL" in "MGI Mammalian Phenotype Level 4 2019" as these names were correct when we created the libraries.
