### ISSUE TITLE
[BUG] Different gmt files are used in Enrichr server and download package

### ISSUE THREAD

**Issue by hsiaoyi0504** [MaayanLab/enrichr_issues#20]
It is originally reported to https://github.com/zqfang/GSEApy/issues/122.
However, it seems to me that the root cause of the issue is probably because the gmt files that we can download from https://maayanlab.cloud/Enrichr/#stats are different from those used in the Enrichr server.

**Comment by maxim-k** [comment]
@hsiaoyi0504  data is the same, as gmt files on #stats are generated from the database every time you request them.
We didn't develop GSEApy package, so I don't know how does 'local' mode of GSEApy work, but from [what I see](https://github.com/zqfang/GSEApy/blob/master/gseapy/enrichr.py#L326) they calculate values in local mode themselves. That's probably the reason whey values are close, but not identical.

**Comment by hsiaoyi0504** [comment]
@maxim-k Thanks for replying to me. However, as I mentioned in the original issue:
> One thing I notice is that the total numbers of genes in PI3K-Akt signaling pathway term (354 and 352) are different in these two modes. Does that mean the gmt files used by the Enrichr sever are different from those we can download from Enrichr sever?

Do you mean that the gmt file of KEGG_2019_HUMAN is probably updated recently? I downloaded the gmt file earlier today.

**Comment by hsiaoyi0504** [comment]
Oh, I checked with the Malaria term. It seems like the GSEApy might have a bug of parsing gmt file.
