### ISSUE TITLE
HuBMAP_ASCT_plus_B_augmented_w_RNAseq_Coexpression Dataset Preparation Details

### ISSUE THREAD

**Issue by ragans** [MaayanLab/enrichr_issues#23]
Can you provide some details on the preparation of the cell type gene sets in the HuBMAP_ASCT_plus_B_augmented_w_RNAseq_Coexpression Dataset.  This would be very helpful for understanding the use of some markers for different cell types.

Thanks very much.

**Comment by AviMaayan** [comment]
Hi @ragans we took the marker gene sets from here: https://hubmapconsortium.github.io/ccf-asct-reporter/ and the added to each set the top 100 genes that mostly co-express with each set (or individual genes) using the ARCHS4 global co-expression matrix from here: https://maayanlab.cloud/archs4/download.html
