### ISSUE TITLE
meaning of combined score

### ISSUE THREAD

**Issue by rachellw** [MaayanLab/enrichr_issues#26]
Hi

I love your website it has given me so much insight into my data. Thanks for setting it up.

I was wondering, how is the combined score calculated please?  I assume it is a combination of the odds ratio and p value and adjusted p value but can't find any details.  

Is there a standard cutoff that people tend to use for combined value (equivalent to the 0.05 people use for p value?)

Thanks again for creating such a useful resource.

best wishes
Rachel

**Comment by AviMaayan** [comment]
Hi @rachellw 

The formula for the combined score is -ln(p-value)*odds-ratio. There is now guide for a good cut off but borderline p-values and very few overlapping genes (less than 3) should not be considered in most cases.

Best,

Avi

**Comment by rachellw** [comment]
HI Avi
Thanks for your speedy and helpful answer
best wishes
Rachel

**Comment by rachellw** [comment]
Thanks so much for your help - I later found the information on calculation of combined score on the website - it was a bit tricky to find as to reveal the description of combined score one has to hover the mouse over the heading of the P value column and to find the description of the p value one has to hover over the heading of the odds ratio column
![image](https://user-images.githubusercontent.com/50137382/130605001-d8ce3313-dfb2-41db-994c-c91141781d9c.png)
