### ISSUE TITLE
[QUESTION] Difference Between ChEA2016 and CHEA Transcription Factor Targets Dataset

### ISSUE THREAD

**Issue by Jiafi** [MaayanLab/enrichr_issues#27]
**Describe the bug**

These two datasets are very similar.  I was wondering exactly what the difference was.  I have been told that the later is a better, cleaned up version of ChEA2016.

https://maayanlab.cloud/Enrichr/geneSetLibrary?mode=text&libraryName=ChEA_2016 vs. https://maayanlab.cloud/static/hdfs/harmonizome/data/cheappi/gene_attribute_edges.txt.gz

Sources: 
https://maayanlab.cloud/Enrichr/#libraries vs. https://maayanlab.cloud/Harmonizome/dataset/CHEA+Transcription+Factor+Targets

**Comment by AviMaayan** [comment]
Please use the ChEA 2022 update library as the most recent version.
