### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by Axale42** [MaayanLab/enrichr_issues#28]
Hi, 
I have a general question regarding enrichR, it's an useful tools.
hovewer, when performing enrichment analysis, I do not always want to use all gene as background, but a selection of genes (Like gene that are only detected by RNA-seq, or gene that are below a cut off of expression)

My question is so, is it possible to change or to give a list of background gene ?

Thanks in advance and again many thanks for this fabulous tool

**Comment by AviMaayan** [comment]
Hi @Axale42,

You can use this Appyter to perform such analysis:
https://appyters.maayanlab.cloud/#/Independent_Enrichment_Analysis

We do not have support for customized backgrounds in the main Enrichr application.

Best,

Avi
