### ISSUE TITLE
[BUG]enrichR not working

### ISSUE THREAD

**Issue by aleph9999** [MaayanLab/enrichr_issues#29]
**Describe the bug**
The R package enrichr function not working

**To Reproduce**
the library loading and function calling function both showed database not responding while the web interface works well

**Expected behavior**
Working enrichR function

**Screenshots**
![image](https://user-images.githubusercontent.com/47076114/138375936-136f32e8-a33a-4ff8-82f5-ff1b9a8fd609.png)

**Desktop (please complete the following information):**
MacOS 
enrichR 3.0

**Additional context**

**Comment by maxim-k** [comment]
@aleph9999 the problem might be that your package is outdated and is using deprecated URLs. You can update it by running `install.packages("enrichR")` or
```
library(devtools)
install_github("wjawaid/enrichR")
```

**Comment by aleph9999** [comment]
Hi, I tried installing the latest version (3.0 from CRAN and GitHub one) and still get same error.

**Comment by AviMaayan** [comment]
Hi @aleph9999, Just tested it from New York City, US and it seems to work... might be your location or internet connection (?) 
![image](https://user-images.githubusercontent.com/12749033/138385179-1096088f-9802-4a8f-8e60-5a5a95680e0b.png)

**Comment by aleph9999** [comment]
Thanks for helping. I guess it might be root CA certificate expiration issue. After I turned off ssl_verifypeer config on httr package it seems working. Sorry for inconvenience.
