### ISSUE TITLE
[BUG] YeastEnrichr service not available

### ISSUE THREAD

**Issue by ChiamYu** [MaayanLab/enrichr_issues#4]
**Describe the bug**
The https://maayanlab.cloud/YeastEnrichr service is not available. 

**To Reproduce**
Go to : https://maayanlab.cloud/YeastEnrichr 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : Chrome

**Comment by AviMaayan** [comment]
Should be back up. Thank you for letting us know!

**Comment by ChiamYu** [comment]
Thank you for fixing this so fast!
