### ISSUE TITLE
scEnrichr repo missing in GitHub

### ISSUE THREAD

**Issue by chprasad** [MaayanLab/enrichr_issues#42]
[Git repo](https://github.com/maayanLab/scEnrichr) listed in [scEnrichr appyter page](https://appyters.maayanlab.cloud/#/scEnrichr) returns a 404. 

Is there a new home for scEnrichr description and/or source?

**Comment by u8sand** [comment]
@chprasad This is an internal repo but in reality it doesn't have much more than what is available in the catalog source which is at: https://github.com/MaayanLab/appyter-catalog/tree/main/appyters/scEnrichr

We'll probably update the link, do let us know if you have further questions

**Comment by u8sand** [comment]
Fixed in https://github.com/MaayanLab/appyter-catalog/commit/6dca33a064108a5e7853fc739d44eedf103e68a7
