### ISSUE TITLE
Reactome Library

### ISSUE THREAD

**Issue by sianfox** [MaayanLab/enrichr_issues#43]
Hi,
I am curious as to why the Reactome library in Enrichr has not been updated since 2016. 
Personally I find this database generally more useful in my work than Kegg for example that you do update.
Thanks
Simon

**Comment by AviMaayan** [comment]
Hi @sianfox thank you for your e-mail. We will prioritize this...

**Comment by AviMaayan** [comment]
Dear @sianfox, 
We just updated the Reactome library in Enrichr.
Cheers,
Avi
