### ISSUE TITLE
could you provide with code of enrichr[BUG]

### ISSUE THREAD

**Issue by FADHLyemen** [MaayanLab/enrichr_issues#45]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
if I have my own background genes, could you provide us with code to compute p-value and others parameters?

why Reactome have 2016? how to get 2022
https://maayanlab.cloud/Enrichr/

**Comment by AviMaayan** [comment]
Hi @FADHLyemen,
We just updated the Reactome library.
Best,
Avi

**Comment by FADHLyemen** [comment]
@AviMaayan thank you, could you release your code? I want to download the library and plot the barplot by my self in ggplot?
how to calculate odd ratio and combined score and old p value?

Thank you for providing all of these service to the community

**Comment by AviMaayan** [comment]
You can try using this Appyter: https://appyters.maayanlab.cloud/Independent_Enrichment_Analysis/
