### ISSUE TITLE
is it possible to search all libraries together via the API

### ISSUE THREAD

**Issue by chubukov** [MaayanLab/enrichr_issues#46]
The only examples on the https://maayanlab.cloud/Enrichr/help#api page involve doing enrichment analysis on only a single gene set library. Of course it's possible to loop over the libraries one at a time but this is orders of magnitude less efficient than the performance one gets with through the browser interface, so it doesn't seem great.

Is there a way to specify multiple libraries in the API? Or is there a nice example of how to download all the libraries and run the enrichment offline?

Thanks.

**Comment by AviMaayan** [comment]
This link might help: https://appyters.maayanlab.cloud/#/Independent_Enrichment_Analysis

**Comment by chubukov** [comment]
Thanks Avi, I was able to get that running.
