### ISSUE TITLE
Can't submit fuzzy set to human Enrichr site

### ISSUE THREAD

**Issue by stmartineau** [MaayanLab/enrichr_issues#47]
I'm trying to submit a fuzzy set to the human Enrichr site, but it doesn't want to take the numbers. It is only giving me to option to submit the gene symbols.

When I paste my list of gene,value into the text box, it converts every row to just the gene when I click submit. 
![enrichr](https://user-images.githubusercontent.com/52297376/194415199-82d9bf7e-a0fb-4556-8596-3904c04f81ee.JPG)

I also tried the enrichr R package and couldn't figure out how to use fuzzy sets.

Here is the list I am trying to submit.
[Spp1_top100.txt](https://github.com/MaayanLab/enrichr_issues/files/9728408/Spp1_top100.txt)

**Comment by AviMaayan** [comment]
Hi @stmartineau it is disabled because we had to upgrade the backend to handle an increasing demand...

**Comment by stmartineau** [comment]
Do you how long it will likely take to be back up?

**Comment by AviMaayan** [comment]
We plan to leave it the way it is for now...
