### ISSUE TITLE
Gene search via the API, is it possible?

### ISSUE THREAD

**Issue by AlfredoKCL** [MaayanLab/enrichr_issues#5]
Dear developers,

I would like to use the gene search tool of the Enrichr webserver via the API. Is this possible? 

Thanks in advance for your help

Best wishes

Alfredo

**Comment by maxim-k** [comment]
@AlfredoKCL you can use [/genemap](https://maayanlab.cloud/Enrichr/genemap?gene=STAT3&json=true) endpoint with two parameters: `gene` for a gene name and (optional) `json=true` to get results in json format.

**Comment by AlfredoKCL** [comment]
@maxim-k  Thank you very much Maxim. I have another question about this. I am not that familiar with the json fomat so I would like to have the output in plaintext. If I set json=false I obtain this but I lose the category information. Is it possible to get the output in plaintext but still grouped by category (e.g. Transcription, pathways, etc) and by source (e.g. for Transcription, ChEA 2016, ENCODE and ChEA Consensus TFs from ChIP-X, ARCHS4 TFs Coexp, etc)?

Alternatively, I imagine I could recreate the menu with the categories from the json output, however, not  being able to do it myself, is there a script to do it?

Thank you very much in advance

Alfredo
