### ISSUE TITLE
Reference for ChEA 2022 datasets

### ISSUE THREAD

**Issue by priyambial123** [MaayanLab/enrichr_issues#51]
Hello

Can you provide the reference for ChEA 2022?. I need to cite for my poster work

Thank you

**Comment by AviMaayan** [comment]
Hi @priyambial123 please cite ChEA3:
Keenan AB, Torre D, Lachmann A, Leong AK, Wojciechowicz ML, Utti V, Jagodnik KM, Kropiwnicki E, Wang Z, Ma'ayan A. ChEA3: transcription factor enrichment analysis by orthogonal omics integration. Nucleic Acids Res. 2019 Jul 2;47(W1):W212-W224. doi: 10.1093/nar/gkz446. PMID: 31114921; PMCID: PMC6602523.
