### ISSUE TITLE
Information about Z-scores should be replaced with odds ration calculation [BUG]

### ISSUE THREAD

**Issue by AviMaayan** [MaayanLab/enrichr_issues#62]
We no longer using the Z-score. It is replaced with the odds ratio. 

This text should be replaced:
<img width="776" alt="Screen Shot 2023-05-17 at 7 36 17 PM" src="https://github.com/MaayanLab/enrichr_issues/assets/12749033/f584b782-5b4f-4d16-8bb8-63767f539458">

The should be the new text for this section:

The **odds ratio** is computed using this formula: oddsRatio = (1.0 * a * d) / Math.max(1.0 * b * c, 1) where:
a- are the overlapping genes
b- genes in the annotated set - overlapping genes 
c- genes in the input set - overlapping genes 
d- 20,000 genes (or total genes in the background) - genes in the annotated set - genes in the input set + overlapping genes

**Comment by ycl6** [comment]
Hi, in the [Enrichr API](https://maayanlab.cloud/Enrichr/help#api) documentation, one of the values returned is Z-score, I am wondering if the API service can return odds ratio instead?

**Comment by ycl6** [comment]
Hi, I have a closer look at the numbers, and it is Odds Ratio in the results, not Z-score. Hence the documentation need updating.
