### ISSUE TITLE
Enrichr does not recognize certain sugarbeet gene names

### ISSUE THREAD

**Issue by sarabehnamian** [MaayanLab/enrichr_issues#69]
I am keen on utilizing Enrichr for my research endeavors. However, I've encountered an issue where Enrichr does not recognize certain sugarbeet gene names, such as 'LOC104894538'. Interestingly, it seems to work fine with other genes that don't carry the 'LOC' prefix, like 'BPGM' (not sugarbeet). This leads me to believe that the gene naming convention could be the underlying problem. A challenge I face is that these sugarbeet gene names don't have alternative identifiers that Enrichr recognizes. I would greatly appreciate any guidance or solutions you can provide.

**Comment by AviMaayan** [comment]
Enrichr is designed to only supports mammalian gene names...
