### ISSUE TITLE
Failed to process user list. (400) [BUG]

### ISSUE THREAD

**Issue by flokraft85** [MaayanLab/enrichr_issues#76]
**Describe the bug**
With every gene list I try, also the example gene list, I got the error "Failed to process user list. (400)". I try it on different PC and in the Edge and Firefox browser.

**To Reproduce**
Enter a gene list in the text-box or clicking on example in the text above the text-box. Pressing submit.

**Expected behavior**
Enrichr should make the enrichment analysis in regards to the submitted gene list.

**Screenshots**
-

**Desktop (please complete the following information):**
Edge and Firefox
Win10

**Smartphone (please complete the following information):**
-

**Additional context**
-

**Comment by usobhi** [comment]
I also have the same issue! I also tried with the example gene list, and I got same error

**Comment by AviMaayan** [comment]
It should be back and working now. Thank you for letting us know about it.
