### ISSUE TITLE
Export function

### ISSUE THREAD

**Issue by denoqo** [MaayanLab/enrichr_issues#8]
Hello, 

There seems to be an issue with the " Export entries to table" function from the web, as below:
```
{
"expired": true
}
```

It's also affecting the R-package enrichR dependent on it.
```
> genelist<-c(c("KRAS", "NF1", "APC"))
> dbs<-c("WikiPathways_2019_Human")
> library(enrichR)
> enrichr(genelist,dbs)
Uploading data to Enrichr... Done.
  Querying WikiPathways_2019_Human... Done.
Parsing results... Done.
$WikiPathways_2019_Human
               X.
1 "expired": true
2               }
```

I guess it's temporary as you guys are updating the tool?

Thanks a lot!
Nick

**Comment by u8sand** [comment]
Thank you for the report, we've been working on ways to deal with more users and our recent attempt at using multiple instances seems to have been premature; we've reverted it for now.

**Comment by AviMaayan** [comment]
It should now work again as expected. Thank you @denoqo for letting us know about this issue.
