### ISSUE TITLE
Odds ratio interpretation

### ISSUE THREAD

**Issue by Matthieubz** [MaayanLab/enrichr_issues#81]
Hello, 

I am using the online version of EnrichR to perform enrichment analyses of differential signatures on Reactome pathways. Could you please provide me details on the calculation and indicate me how to interpret the Odds.Ratio column in the output ? 

Many thanks

**Comment by enryH** [comment]
I have a question how to read the documentation of the odds ratio from the[ help page](https://maayanlab.cloud/Enrichr/help#background):

> where: a are the overlapping genes, b are the genes in the annotated set - overlapping genes, c- are the genes in the input set - overlapping genes, and d- are the 20,000 genes (or total genes in the background) - genes in the annotated set - genes in the input set + overlapping genes

How should one read the pluses (+) and minus (-) in the text?

For example:

What is d?
- 20,000 genes (or no. of background genes) minus genes in the annotated set minus genes in the input minus genes overlapping?
- if that is true, then I would write minus and plus
- and remove the `d-` minus after d. 

If it is a mix of minus (-) in the mathematical sense and hyphens, it needs some clarifications:) It's a great tool and the documentation is in many parts already super great!

**Comment by lachmann12** [comment]
Hi,

the odds ratio is computed like so:

```
int totalBgGenes = 20000; // hardcoded
int gmtListSize = length of gene set from library
int numGenelist = length of gene set from user input
int a = numOverlap;
int b = gmtListSize - numOverlap;
int c = numGenelist - numOverlap;
int d = totalBgGenes - numGenelist - gmtListSize + numOverlap;
double oddsRatio = (1.0 * a * d) / Math.max(1.0 * b * c, 1);			
```

I hope this helps.

Best,
Alex

**Comment by enryH** [comment]
Yes thanks! That clarifies it. Will you update the help text accordingly? (I would opt for writing minus and plus as words to make it clear - and/or link the function on GitHub?)

**Comment by AviMaayan** [comment]
Will do. Thank you so much for the helpful feedback. It is much appreciated!
