### ISSUE TITLE
[BUG] Failed to process user list

### ISSUE THREAD

**Issue by XimenaMaVa** [MaayanLab/enrichr_issues#84]
I’ve been trying to upload my background file copying and pasting from different formats (csv, txt) and it always shows that error☹ I also tried in 2 different browsers (Chrome and Firefox).
 ![error enrichr](https://github.com/MaayanLab/enrichr_issues/assets/159741675/c452ada7-3f11-442b-a8bc-f71d32646a29)

About the genes, when I copy and paste them whitout background, this results are shown I thought it was my internet conection but the last one does have lists; so my question is: is it normal that the results are shown like this?

![error enrichr 2](https://github.com/MaayanLab/enrichr_issues/assets/159741675/3eeda01d-406a-4b15-bfad-2a02ebdc494e)

**Comment by AviMaayan** [comment]
Hi @XimenaMaVa it sounds like your gene sets are not formatted correctly. Can you share these gene sets with me? You can send the gene sets via e-mail to avi.maayan@mssm.edu.

**Comment by AviMaayan** [comment]
Hi Ximena,

You need to remove the numbers before the gene names in the "die_down.txt" file. Your background is formatted correctly but looks weird because it has over 100,000 gene names. Typically, backgrounds should have much less genes.

Best,

Avi

**Comment by XimenaMaVa** [comment]
Thank you so much!
Do I have to delete it from the text file? I had deleted it from excel and
from there I copied and pasted it in Enrichr.
Sorry for all the questions it is my first time doing this 😞
And also thanks for the information about the background!

**Comment by AviMaayan** [comment]
Yes. The text file should just have the gene name in each row without the number column.
