### ISSUE TITLE
CLARIFICATION: gene set descriptions

### ISSUE THREAD

**Issue by h-samee** [MaayanLab/enrichr_issues#88]
Hi, Thanks for this amazing resource. For some _GTEx-related libraries_, it would be nice to get additional clarification on the background gene sets and the direction of comparisons. Below, we have given some specific examples:
1. In "GTEx_Tissues_V8_2023," does the gene set "Atrial Appendage Female 20-29 Up" give us genes up-regulated in the Atrial Appendage of 20-29 yo Females compared to **_all other non-atrial-appendage_** samples in the data, **_including left ventricles_**? This is important information since atrial appendages and left ventricles are both from the heart.
2. In "GTEx_Aging_Signatures_2021," does the gene set "GTEx SalivaryGland 20-29 vs 40-49 Up" give us genes up-regulated in the salivary gland of 40-49 yo compared to 20-29 yo? Or, are these genes up-regulated in 20-29 yo compared to 40-49 yo?

**Comment by AviMaayan** [comment]
1. all other non-atrial-appendage samples in the data
2. genes up-regulated in the salivary gland of 40-49 yo compared to 20-29 yo

**Comment by h-samee** [comment]
Thanks so much!
