### ISSUE TITLE
Libraries categories

### ISSUE THREAD

**Issue by AaronBlare** [MaayanLab/enrichr_issues#91]
Hello!
Thanks for a very useful tool!

I have a question, not a bug:

When using modEnrichr, the results are grouped into 8 categories: Transcription, Pathways, Ontologies, Diseases/Drugs, Cell Types, Misc, Legacy, Crowd.
Is there anywhere I can find information on how all the available 227 libraries are grouped into these categories?

**Comment by AviMaayan** [comment]
Hi @AaronBlare there is no specific method to determine the category. It is done manually based on background knowledge expertise.
