### ISSUE TITLE
[BUG] Link from metadata search where term as a hyphen do not work

### ISSUE THREAD

**Issue by AviMaayan** [MaayanLab/enrichr_issues#96]
**Describe the bug**

**To Reproduce**
1. Go to 'metadata search'
2. Type 'parkinson'
3. Trying clicking on link to Enrichr from GWAS Catalog Parkinson's Disease
4. See error (link does not work)
<img width="823" alt="Screenshot 2024-10-19 at 11 28 15 PM" src="https://github.com/user-attachments/assets/6a4fddf1-1f59-4e55-b7fb-affde77d8176">

**Comment by jeevangelista** [comment]
fixed issue on single quotes
