### ISSUE TITLE
package not available on CRAN

### ISSUE THREAD

**Issue by billila** [MaayanLab/enrichr_issues#98]
Hi!
I wanted to ask if the `enrichR` package will become available on CRAN again.
Thank you!

https://cran.r-project.org/web/packages/enrichR/index.html

**Comment by AviMaayan** [comment]
You can try to use this R library that we created: https://github.com/MaayanLab/speedr

**Comment by AviMaayan** [comment]
The enrichR library was not created by us, but I will look into why it was archived...

**Comment by billila** [comment]
thanks for your answer!

**Comment by u8sand** [comment]
The actual repo of enrichR (the R package) is https://github.com/wjawaid/enrichR

an outstanding PR fixes it https://github.com/wjawaid/enrichR/pull/84

but the maintainer needs to accept it and redeploy to CRAN.
You can install it straight off of github following their instructions (with devtools)

devtools can be installed from CRAN if you don't already have it
```
install.packages("devtools")
```

```
library(devtools)
install_github("wjawaid/enrichR")
```

**Comment by billila** [comment]
thanks for your help!
